export enum STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
}

export enum FILE_STATUS {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
}

export enum PERMISSION {
  VIEW_USERS = 'VIEW_USERS',
  VIEW_USER = 'VIEW_USER',
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  VIEW_ROLES = 'VIEW_ROLES',
  VIEW_ROLE = 'VIEW_ROLE',
  CREATE_ROLE = 'CREATE_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  VIEW_PRODUCTS = 'VIEW_PRODUCTS',
  VIEW_PRODUCT = 'VIEW_PRODUCT',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  VIEW_ORDERS = 'VIEW_ORDERS',
  VIEW_ORDER = 'VIEW_ORDER',
  CREATE_ORDER = 'CREATE_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',
}
